jwts:
  secretKey: "c21hcnQtZWR1Y2F0aW9uLWJhY2tlbmQtc2VjcmV0a2V5LWZvci1qd3Q="

druid:
  driver: "org.postgresql.Driver"
  username: "postgres"
  password: "@Abc123456"
  url: "jdbc:postgresql://118.89.136.119:5432/smart_edu?currentSchema=data"
  initsize: 5
  minidle: 3